### ISSUE TITLE
does not work with python version 3.12

### ISSUE THREAD

**Issue by EL1TRA** [VadimBoev/freegpt-webui-v2#10]
it worked on version 3.11.5
but...

Traceback (most recent call last):
  File "H:\GPT4\freegpt-webui-v2\run.py", line 5, in <module>
    from server.backend import Backend_Api
  File "H:\GPT4\freegpt-webui-v2\server\backend.py", line 7, in <module>
    from g4f import __init__, ChatCompletion
  File "H:\GPT4\freegpt-webui-v2\g4f\__init__.py", line 3, in <module>
    from .models    import Model, ModelUtils, _all_models
  File "H:\GPT4\freegpt-webui-v2\g4f\models.py", line 4, in <module>
    from .Provider   import BaseProvider, RetryProvider
  File "H:\GPT4\freegpt-webui-v2\g4f\Provider\__init__.py", line 30, in <module>
    from .MyShell         import MyShell
ModuleNotFoundError: No module named 'g4f.Provider.MyShell'

**Comment by EL1TRA** [comment]
but I have everything installed and the right version

**Comment by VadimBoev** [comment]
hi. Most likely, this problem is related to copying files. The myShell file.py could be replaced, pay attention to this
