### ISSUE TITLE
Getting babel error

### ISSUE THREAD

**Issue by Mylinde** [VadimBoev/freegpt-webui-v2#19]
What do i wrong? Getting babel error. Python 3.10.12

`mario@mario-pc:~/freegpt-webui-v2$ python3 run.py
Traceback (most recent call last):
  File "/home/mario/freegpt-webui-v2/run.py", line 22, in <module>
    create_babel(app)
  File "/home/mario/freegpt-webui-v2/server/babel.py", line 24, in create_babel
    compile_translations()
  File "/home/mario/freegpt-webui-v2/server/babel.py", line 39, in compile_translations
    result = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pybabel'
`

**Comment by Mylinde** [comment]
Solved. python3-babel was not installed.
