### ISSUE TITLE
error

### ISSUE THREAD

**Issue by VaMPIRESqq** [VadimBoev/freegpt-webui-v2#25]
command: `python3 run.py`
error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 617, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 956, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 815, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 861, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (Babel 2.14.0 (/home/lse/.local/lib/python3.11/site-packages), Requirement.parse('Babel==2.10.3'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pybabel", line 33, in <module>
    sys.exit(load_entry_point('Babel==2.10.3', 'console_scripts', 'pybabel')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lse/.local/lib/python3.11/site-packages/babel/messages/frontend.py", line 979, in main
    return CommandLineInterface().run(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lse/.local/lib/python3.11/site-packages/babel/messages/frontend.py", line 905, in run
    return cmdinst.run()
           ^^^^^^^^^^^^^
  File "/home/lse/.local/lib/python3.11/site-packages/babel/messages/frontend.py", line 192, in run
    for errors in self._run_domain(domain).values():
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lse/.local/lib/python3.11/site-packages/babel/messages/frontend.py", line 256, in _run_domain
    catalogs_and_errors[catalog] = catalog_errors = list(catalog.check())
                                                    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lse/.local/lib/python3.11/site-packages/babel/messages/catalog.py", line 744, in check
    errors = message.check(catalog=self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lse/.local/lib/python3.11/site-packages/babel/messages/catalog.py", line 205, in check
    from babel.messages.checkers import checkers
  File "/home/lse/.local/lib/python3.11/site-packages/babel/messages/checkers.py", line 173, in <module>
    checkers: list[Callable[[Catalog | None, Message], object]] = _find_checkers()

^^^^^^^^^^^^^^^^
  File "/home/lse/.local/lib/python3.11/site-packages/babel/messages/checkers.py", line 160, in _find_checkers
    from pkg_resources import working_set
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3248, in <module>
    @_call_aside
     ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3223, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3261, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 619, in _build_master
    return cls._build_from_requirements(__requires__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 632, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
                             ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1044, in __init__
    self.scan(search_path)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1077, in scan
    self.add(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1096, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in hashcmp
    self.parsed_version,
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2679, in parsed_version
    self._parsed_version = parse_version(self.version)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.x.x'
(package: sysmontask)
Traceback (most recent call last):
  File "/home/lse/freegpt-webui-v2/run.py", line 22, in <module>
    create_babel(app)
  File "/home/lse/freegpt-webui-v2/server/babel.py", line 24, in create_babel
    compile_translations()
  File "/home/lse/freegpt-webui-v2/server/babel.py", line 45, in compile_translations
    raise Exception(
Exception: Compiling translations failed:

**Comment by Mylinde** [comment]
looks like python3-babel is missing

**Comment by VaMPIRESqq** [comment]
pip show Babel
Name: Babel
Version: 2.14.0
Summary: Internationalization utilities
Home-page: https://babel.pocoo.org/
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD-3-Clause
Location: /home/lse/.local/lib/python3.11/site-packages
Requires:
Required-by: aiogram, flask-babel

and that's exactly this error

**Comment by Mylinde** [comment]
Isn't an error, it's just not installed.

**Comment by Mylinde** [comment]
flask-babel is also present?

**Comment by VaMPIRESqq** [comment]
> flask-babel is also present?

yes, he was working 2 days ago, but now he's gone

**Comment by VadimBoev** [comment]
he swears at Babel. If it's linux, then if you haven't used a virtual environment, then maybe it's worth doing (python 3 -m vent valve, source venv/bin/activate, and so on). I suspect there is some kind of problem with the packages.

**Comment by VadimBoev** [comment]
Try pip install babel && pip install flask-babel

**Comment by VaMPIRESqq** [comment]
reinstalling system helps me 😸
